services:
  - type: web
    name: semillero-inteligente
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Backend.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PORT
        value: 5000
      - key: MQTT_USER
        sync: false
      - key: MQTT_PASS
        sync: false
      - key: MQTT_BROKER
        sync: false
      - key: MQTT_PORT
        value: 8884
      - key: MQTT_TOPIC_SENSORS
        value: esp32/sensores
      - key: MQTT_TOPIC_ACTUADORES
        value: esp32/actuadores
      - key: GEMINI_API_KEY
        sync: false
